jobs:
  bincheck:
    defaults:
      run:
        shell: bash -euxo pipefail {0}
    name: Binary Static Analysis
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: recursive
    - continue-on-error: true
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - continue-on-error: true
      name: Display Python version
      run: 'python -c "import sys; print(sys.version)"

        '
    - continue-on-error: true
      name: Install build dependencies
      run: 'scripts/ubuntu_install_protobuf.sh

        '
    - continue-on-error: true
      name: Build subzero CORE
      run: 'scripts/build_core.sh

        '
    - continue-on-error: true
      name: Run binary static analysis
      run: 'scripts/bsa_check_core.sh core/build

        '
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.9
name: Binary Static Analysis
on:
  repository_dispatch:
    types: trigger-ga___binary-static-analysis.yml
