jobs:
  fuzzing-regression-test:
    defaults:
      run:
        shell: bash -euxo pipefail {0}
    name: Fuzzing Regression Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: recursive
    - continue-on-error: true
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - continue-on-error: true
      name: Display Python version
      run: 'python -c "import sys; print(sys.version)"

        '
    - continue-on-error: true
      name: Install dependencies
      run: scripts/ubuntu_install_protobuf.sh
    - continue-on-error: true
      name: Setup Clang
      uses: egor-tensin/setup-clang@v1.4
      with:
        platform: x64
        version: latest
    - continue-on-error: true
      name: Build Subzero Core (ASAN+UBSAN+FUZZER)
      run: 'export CC=`which clang`

        export CXX=`which clang++`

        scripts/build_core.sh -DENABLE_ASAN=ON -DENABLE_UBSAN=ON -DENABLE_FUZZER=ON

        '
    - continue-on-error: true
      name: Run Subzero CORE Fuzzing regression test
      run: 'cd ${{ github.workspace }}

        ./core/build/subzero_fuzzer-testnet ./core/fuzzing_regression_test_inputs/*

        '
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.9
name: Fuzzing Regression Test
on:
  repository_dispatch:
    types: trigger-ga___fuzzing-regression-test.yml
