jobs:
  java-unit-test:
    defaults:
      run:
        shell: bash -euxo pipefail {0}
    name: Java Unit Test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: recursive
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Run Unit tests
      run: 'cd ${{ github.workspace }}/java

        ./gradlew test --info

        '
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.9
name: Java Unit Test
on:
  repository_dispatch:
    types: trigger-ga___java-test.yml
