jobs:
  signtx-test-asan:
    defaults:
      run:
        shell: bash -euxo pipefail {0}
    name: SignTx Test with ASAN
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
        submodules: recursive
    - continue-on-error: true
      name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - continue-on-error: true
      name: Display Python version
      run: 'python -c "import sys; print(sys.version)"

        '
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - continue-on-error: true
      name: Install dependencies
      run: scripts/ubuntu_install_protobuf.sh
    - continue-on-error: true
      name: Build Java
      run: 'cd ${{ github.workspace }}/java

        ./gradlew clean build --info

        '
    - continue-on-error: true
      name: Build Subzero Core with ASAN
      run: scripts/build_core.sh -DENABLE_ASAN=ON
    - continue-on-error: true
      name: Run Subzero CORE with ASAN
      run: 'cd ${{ github.workspace }}

        ./core/build/subzero-testnet &

        '
    - continue-on-error: true
      name: Run SignTx Test with ASAN
      run: 'cd ${{ github.workspace }}

        sleep 10

        rm -f /tmp/signtx-test-asan.out

        java -jar ./java/gui/build/libs/gui-1.0.0-SNAPSHOT-shaded.jar --signtx-test
        | tee /tmp/signtx-test-asan.out

        grep -qv "ALL TESTS PASSED" /tmp/signtx-test-asan.out || exit 1

        '
    strategy:
      fail-fast: false
      matrix:
        python-version:
        - 3.9
name: SignTx Regression Test with ASAN
on:
  repository_dispatch:
    types: trigger-ga___signtx-test-asan.yml
